### ISSUE TITLE
Implement a server/client prototype 

### ISSUE THREAD

**Issue by alma89** [aosmanovic3/AOOP_2015#3]

**Comment by dseebacher** [comment]
## protocol
message from client to the server
* before joined  _join game_
* wind actions as _wind north_..

message from the server to the client
* on start: _game board_
* wind properties like _direction_, _strength_
* _position_ of all mice

**Comment by dseebacher** [comment]
The prototype is based on _natty_ and uses JSON as the message format. A message must have a _type_ field and could looks like thit:
```json
{
  "type": "ping",
  "someOtherField": "foo"
}
```

**Comment by dseebacher** [comment]
A simple _ping/pong_ server was implemented :)
